---
name: dbedia
version: 0.01
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: interface to dbedia.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::Cache: 0
  Carp: 0
  Class::Accessor::Fast: 0
  IO::Uncompress::Gunzip: 0
  JSON::XS: 0
build_requires:
  File::Spec: 0
  LWP::Simple: 0
  Test::Exception: 0
  Test::More: 0
provides:
  dbedia:
    file: lib/dbedia.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
